### ISSUE TITLE
Trier les emotes

### ISSUE THREAD

**Issue by Lindwen** [DieuKoukiFactori/discord-emojis-collector#2]
Il serait utile de lors de la création du dossier output, lorsqu'on choisit de télécharger les emotes d'une guilde de qu'un dossier se créer dans le dossier output avec le nom de la guilde.
Par exemple je choisis les emotes du serveur "Test1" :
output/Test1/emote.png
et du coup s'il y a plusieurs serveurs :
output/Test1/emote.png
output/Test2/emote.png

**Comment by Woomymy** [comment]
Oui, ça serait pratique car parfois 2serveurs ont des emotes du même nom mais ont pas le meme contenu (j'ai l'impression que si il en voit du meme nom il redl pas).

**Comment by KoukiFactori** [comment]
@Woomy4680-exe Le programme écrasera l'ancien emote pour le remplacer par le nouveau comme c'est le même nom de fichier

**Comment by Woomy4680-exe** [comment]
Oui bah si tu dl 2 servs à la suite du coup ça pose problème  après c'est pas une priorité

**Comment by KoukiFactori** [comment]
Fini ! C'est dispo sur la master, bonne journée

**Comment by Woomymy** [comment]
Ok nickel

**Comment by Woomy4680-exe** [comment]
Merci mossieur le loli
